### ISSUE TITLE
Add a configuration parameter to only allow local connections

### ISSUE THREAD

**Issue by Dalbasar** [albertz/background-zmq-ipython#10]
By default, the underlying sockets are intialized to accept connections from remote hosts. On Windows this means that a Dialog will pop up asking the user whether the firewall should allow remote connections to the ipython kernel. Since there are many use cases where you would want to use the background ipython kernel from a different process, but not from a remote machine, it makes sense add a parameter to the `init_ipython_kernel` method that enables binding to `localhost` only and prevent the firewall popup from appearing on Windows.
Maybe this should even be the default behavior.

**Comment by albertz** [comment]
Fixed via #12.
