### ISSUE TITLE
Cannot see stdout on my jupyter client

### ISSUE THREAD

**Issue by tinmarino** [albertz/background-zmq-ipython#2]
Hi, wonderful job, it works perfect here (Ubunbu 19.10).

1. I cannot see the output of print(42) but I see the output of 42 like a reply
    I think is is due to a lack of init_io() <- https://github.com/ipython/ipykernel/blob/7b2727d827a95d2059c9d9d9354899feabb642ee/ipykernel/kernelapp.py#L370-L375

2. (Easy fix) The connection file is written  is the current directory. For two lines, it could be in the default jupyter runtime dir (`/run/user/1000/jupyter` on my machine) <- https://github.com/ipython/ipykernel/blob/7b2727d827a95d2059c9d9d9354899feabb642ee/ipykernel/kernelapp.py#L136-L138

I am looking to fix 1. Do you experience the same or is it due to my conf ?
I am currently including  your code (with a pip soft dependency) from a ipython@xterm@tkinter window to debug a GUI is user did not think to run this last with a clean ipython instance: https://github.com/tinmarino/abism/blob/master/abism/plugin/xterm_console.py
Really helpfull as completion works.

**Comment by tinmarino** [comment]
A feedback from my use:
* right, the GUI (I am developing to visualize images)
* left the jupyter client (connected to background-zmq-ipython creating in a thread in my GUI instance)
* The GUI parent terminal (i.e your kernel grand-parent). This old dude is receiving the output as pty stuff are still connected.

![abism_jupyter_2](https://user-images.githubusercontent.com/6123962/73576522-6544b080-4459-11ea-847a-ec5971e0084d.png)

If a clean threaded way is hard for stdout (maybe it should signal the client) ? I will trick the kernel to plug it the the terminal I known at priori.

Anyway, you've got a satisfied user. Thanks for the pretty pip sharing !

**Comment by albertz** [comment]
I'm happy that this is useful to you! :) Let's move the further discussion to the individual pull requests.
Btw, I guess your code is [here](https://github.com/tinmarino/abism/blob/master/abism/plugin/window_xterm.py) now. I see that you call `init_ipython_kernel` itself in a background thread. That should not be needed, as `init_ipython_kernel` will itself also start its own thread already.

**Comment by albertz** [comment]
Closing here now. If you have some further questions, just write them anyway.

**Comment by tinmarino** [comment]
Thank to have a look at my code. I will remove the thread creation. I should have watched your `main.py`.
