### ISSUE TITLE
Avoid setting environment variables?

### ISSUE THREAD

**Issue by user202729** [albertz/background-zmq-ipython#5]
I suggest adding

https://github.com/albertz/background-zmq-ipython/blob/8084b9a2ba16220c7b3e72e08ee1ac84ff336336/kernel.py#L34-L42

    def init_environment(self):
        pass

so that IPython doesn't set some environment variables (such as `PAGER=cat`), that we don't need anyway. (I think? May need more test)

**Comment by albertz** [comment]
Yes, probably a good idea.

Do you want to make a PR? Or should I do this change?

**Comment by user202729** [comment]
You should do the change, then.
